In [14]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import keras
from keras.datasets import cifar100
from keras import applications
from __future__ import print_function
from keras import optimizers
from keras.models import Sequential,Input,Model
from keras.models import load_model #save and load models
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D
from sklearn.preprocessing import LabelEncoder
import keras.backend as k

In [15]:
df = pd.read_csv('uber_census.csv', encoding = "ISO-8859-1", engine='python')
data = df
print(data.shape)
print(data.dtypes)
df1 = data

(14250, 8)
hour                            int64
lat                           float64
long                          float64
base                           object
MedianIncomeByPlaceofBirth    float64
MedianIncome                  float64
AvgPopulation                 float64
UserGroup                       int64
dtype: object


In [16]:
df1.head()

hour      lat     long  ... MedianIncome  AvgPopulation  UserGroup
0     4  40.6758 -73.8189  ...      58707.0         6342.0          0
1    19  40.7641 -73.9906  ...      74236.0         6681.0          1
2    17  40.7837 -73.8458  ...      41463.0         3862.0          0
3    20  41.0290 -73.7744  ...      77070.0         7756.0          1
4    51  40.7325 -73.8565  ...      50744.0         4531.0          0

[5 rows x 8 columns]

In [17]:
names_cloud = data.columns.tolist()
print(names_cloud)
X = np.array(data[names_cloud])
print(X.shape)

['hour', 'lat', 'long', 'base', 'MedianIncomeByPlaceofBirth', 'MedianIncome', 'AvgPopulation', 'UserGroup']
(14250, 8)


In [18]:
# fig = plt.figure(figsize=(20,20))
# cols = 5
# rows = (float(data.shape[1]) / cols)
# for i, column in enumerate(data.columns):
#     a = fig.add_subplot(rows, cols, i + 1)
#     a.set_title(column)
#     if data.dtypes[column] == np.object:
#         data[column].value_counts().plot(kind="bar", axes=a)
#     else:
#         data[column].hist(axes=a)
#         plt.xticks(rotation="vertical")
# plt.subplots_adjust(hspace=0.7, wspace=0.2)

In [19]:
y = (data['UserGroup']).values
print(pd.value_counts(pd.Series(y)))
data.drop('UserGroup',axis=1, inplace =True,)

1    7182
0    7068
dtype: int64


In [20]:
categorical_features = data.select_dtypes(include=['object']).columns
print(categorical_features)
ohc_category = ['base']
df_ohc = pd.get_dummies(data, columns = ohc_category)
print(df_ohc.shape)
df_ohc.head()

Index(['base'], dtype='object')
(14250, 9)


hour      lat     long  ...  base_B02512  base_B02598  base_B02617
0     4  40.6758 -73.8189  ...            0            0            1
1    19  40.7641 -73.9906  ...            0            1            0
2    17  40.7837 -73.8458  ...            0            0            1
3    20  41.0290 -73.7744  ...            0            1            0
4    51  40.7325 -73.8565  ...            0            0            1

[5 rows x 9 columns]

In [21]:
names_x = df_ohc.columns.tolist()
print("Target Variable: UserGroup")
print("Predictors: "+str(names_x))
x = np.array(df_ohc[names_x])
print("Number of data samples : {0:d}".format(x.shape[0]))
print("Number of Predictor Features : {0:d}".format(x.shape[1]))
#df_ohc["Age"] = df_ohc["Age"].astype(str).astype(float)
# from google.colab import files
# df_ohc.to_csv('df.csv')
# files.download('df.csv')
df_ohc[names_x]

Target Variable: UserGroup
Predictors: ['hour', 'lat', 'long', 'MedianIncomeByPlaceofBirth', 'MedianIncome', 'AvgPopulation', 'base_B02512', 'base_B02598', 'base_B02617']
Number of data samples : 14250
Number of Predictor Features : 9


hour      lat     long  ...  base_B02512  base_B02598  base_B02617
0         4  40.6758 -73.8189  ...            0            0            1
1        19  40.7641 -73.9906  ...            0            1            0
2        17  40.7837 -73.8458  ...            0            0            1
3        20  41.0290 -73.7744  ...            0            1            0
4        51  40.7325 -73.8565  ...            0            0            1
...     ...      ...      ...  ...          ...          ...          ...
14245     9  40.8872 -73.8642  ...            0            0            1
14246    30  40.6847 -73.9442  ...            0            0            1
14247     6  40.8318 -73.9038  ...            0            1            0
14248    48  40.6341 -73.9054  ...            0            1            0
14249    20  40.6723 -73.8912  ...            0            1            0

[14250 rows x 9 columns]

In [22]:
df_ohc.dtypes

hour                            int64
lat                           float64
long                          float64
MedianIncomeByPlaceofBirth    float64
MedianIncome                  float64
AvgPopulation                 float64
base_B02512                     uint8
base_B02598                     uint8
base_B02617                     uint8
dtype: object

In [23]:
x = x.astype('float32')
x = x/255
batch_size = 64 #upto us
epochs = 200
lrate = 0.001
decay = 1e-7 
data_size = 2000
ns = 10 #number of shadow models for one data_size
nh = 8 #number of hidden layers
nout = 1
seed = 9
np.random.seed(seed)
sh = np.arange(x.shape[0])
np.random.shuffle(sh)
target_rep = np.zeros((1,x.shape[0]))
target_rep[0,:] = sh
print(sh)

[  922 10216 10754 ...  6782  4444  8574]


In [24]:
from tensorflow.keras.optimizers import Adam
k.clear_session()
xtr_target = x[sh[:data_size]]
ytr_target = y[sh[:data_size]]
xts_target = x[sh[data_size:data_size*2]]
yts_target = y[sh[data_size:2*data_size]]
shadow_rep = np.zeros((20,x.shape[0]-2*data_size))
sh1 = sh[2*data_size:]
xtr_att = np.zeros((2*data_size*ns,1))
ytr_att = np.zeros((2*data_size*ns,1))
xtr_att_truelabels = np.zeros((2*data_size*ns,))
model_target = Sequential()
model_target.add(Dense(nh, input_shape =(x.shape[1],), activation='sigmoid', name = 'hidden'))
model_target.add(Dense(1, activation='sigmoid', name = 'output'))
opt = Adam(lr=lrate, decay=decay) 
model_target.compile(loss='binary_crossentropy',
                  optimizer=opt,
                  metrics=['accuracy'])
print(model_target.summary())
hist_target = model_target.fit(xtr_target, ytr_target,
                  batch_size = batch_size,
                  epochs = epochs,
                  validation_data=(xts_target, yts_target), shuffle=True, verbose=0)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden (Dense)              (None, 8)                 80        
                                                                 
 output (Dense)              (None, 1)                 9         
                                                                 
Total params: 89
Trainable params: 89
Non-trainable params: 0
_________________________________________________________________
None


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [25]:
print('\n\nFor target model with training datasize = %d'%data_size)
print('Training accuracy = ', hist_target.history['accuracy'][-1])
print('Validation accuracy = ', hist_target.history['val_accuracy'][-1])
model_target_name = 'Uber_Census_target_'+str(data_size)+'.h5'
model_target.save(model_target_name)
ytemp_tr_target = model_target.predict(xtr_target)
ytemp_ts_target = model_target.predict(xts_target)
xts_att = np.vstack((ytemp_tr_target,ytemp_ts_target))
yts_att = np.zeros((2*data_size,1))
yts_att[data_size:2*data_size] = 1  
xts_att_truelabels = np.vstack((ytr_target,yts_target))
xts_att_dict = {'xts_att':xts_att,'yts_att':yts_att,'xts_att_truelabels':xts_att_truelabels}
fname = './att_test_data_'+str(data_size)
np.save(fname,xts_att_dict)
datafile = './Uber_Census_target_'+str(data_size)
np.save(datafile,target_rep)



For target model with training datasize = 2000
Training accuracy =  0.9679999947547913
Validation accuracy =  0.9620000123977661


In [ ]:
for i in np.arange(ns):
    np.random.shuffle(sh1)
    shadow_rep[i,:] = sh1
    xtr_shadow = x[sh1[:data_size]]
    ytr_shadow = y[sh1[:data_size]]
    xts_shadow = x[sh1[data_size:2*data_size]]
    yts_shadow = y[sh1[data_size:2*data_size]]
    model_shadow = Sequential()
    model_shadow.add(Dense(nh, input_shape =(x.shape[1],), activation='sigmoid', name = 'hidden'))
    model_shadow.add(Dense(1, activation='sigmoid', name = 'output'))
    opt = Adam(learning_rate=lrate, decay=decay) 
    model_shadow.compile(loss='binary_crossentropy',
                  optimizer=opt,
                  metrics=['accuracy'])
    if i == 0:
        print("Shadow Model Summary")
        print(model_shadow.summary())
    hist_shadow = model_shadow.fit(xtr_shadow, ytr_shadow,
                  batch_size = batch_size,
                  epochs = epochs,
                  validation_data=(xts_shadow, yts_shadow), shuffle=True, verbose=0)
    print("Shadow model no: %d"%i)
    print('\n\nFor shadow model with training datasize = %d'%data_size)
    print('Training accuracy = ', hist_shadow.history['accuracy'][-1])
    print('Validation accuracy = ', hist_shadow.history['val_accuracy'][-1])
    ytemp11 = model_shadow.predict(xtr_shadow)
    ytemp22 = model_shadow.predict(xts_shadow)
    model_shadow_name = 'Uber_Census_shadow_'+str(data_size)+'_'+str(i)+'.h5'
    print(model_shadow_name)
    model_shadow.save(model_shadow_name)    

    print(ytemp11)
    print(ytemp22)

    xtr_att[i*2*data_size:(i+1)*2*data_size] = np.vstack((ytemp11,ytemp22))
    ytr_att[((i*2)+1)*data_size:(i+1)*2*data_size] = 1
    print('****')
    print(ytr_shadow)
    print(yts_shadow)
    print( np.hstack((ytr_shadow,yts_shadow)))
    xtr_att_truelabels[i*2*data_size:(i+1)*2*data_size] = np.hstack((ytr_shadow,yts_shadow))
datafile = './data_adult_shadow_'+str(data_size)
np.save(datafile,shadow_rep)
xtr_att_dict = {'xtr_att':xtr_att,'ytr_att':ytr_att,'xtr_att_truelabels':xtr_att_truelabels}
fname = './att_train_data_'+str(data_size)
np.save(fname,xtr_att_dict)

Shadow Model Summary
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 hidden (Dense)              (None, 8)                 80        
                                                                 
 output (Dense)              (None, 1)                 9         
                                                                 
Total params: 89
Trainable params: 89
Non-trainable params: 0
_________________________________________________________________
None
Shadow model no: 0


For shadow model with training datasize = 2000
Training accuracy =  0.9564999938011169
Validation accuracy =  0.9585000276565552
Uber_Census_shadow_2000_0.h5
[[0.05803555]
 [0.77521676]
 [0.0542182 ]
 ...
 [0.1735133 ]
 [0.5117556 ]
 [0.26899558]]
[[0.9766689 ]
 [0.8105086 ]
 [0.179382  ]
 ...
 [0.09829387]
 [0.02164042]
 [0.04500994]]
****
[0 1 0 ... 0 1 0]
[1 1 0 ... 0 0 0]
[0 1 0 ... 0 0 0]
Shadow mod

In [ ]:
model_attack = Sequential()
model_attack.add(Dense(nh, input_shape = (xtr_att.shape[1],), activation='sigmoid', name = 'hidden'))
model_attack.add(Dense(1, activation='sigmoid', name = 'output'))
opt = Adam(learning_rate=lrate, decay=decay) 
model_attack.compile(loss='binary_crossentropy',
                  optimizer=opt,
                  metrics=['accuracy'])
print("Attack Model Summary")
print(model_attack.summary())
hist_attack = model_attack.fit(xtr_att, ytr_att,
                  batch_size = batch_size,
                  epochs = epochs,
                  validation_data=(xts_att, yts_att), shuffle=True, verbose=0)
print('\n\nFor attack model with training datasize = %d'%xtr_att.shape[0])
print('Training accuracy = ', hist_shadow.history['accuracy'][-1])
print('Validation accuracy = ', hist_shadow.history['val_accuracy'][-1])